<?php


/**
 * Skeleton subclass for representing a row from the 'wow_character_class_spec' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * czw, 11 mar 2010, 01:19:16
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowCharacterClassSpec extends BaseWowCharacterClassSpec {

} // WowCharacterClassSpec
