<?php


/**
 * Skeleton subclass for performing query and update operations on the 'wow_character_profession' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * śro, 10 mar 2010, 00:31:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowCharacterProfessionPeer extends BaseWowCharacterProfessionPeer {

} // WowCharacterProfessionPeer
