<?php


/**
 * Skeleton subclass for representing a row from the 'wow_character_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * śro, 10 mar 2010, 00:31:23
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowCharacterItem extends BaseWowCharacterItem {
  public static $slotToRankTranslationTable = array(
    0  => 1,
    1  => 2,
    2  => 3,
    3  => 6,
    4  => 5,
    5  => 10,
    6  => 11,
    7  => 12,
    8  => 8,
    9  => 9,
    10 => 13,
    11 => 14,
    12 => 15,
    13 => 16,
    14 => 4,
    15 => 17,
    16 => 18,
    17 => 19,
    18 => 7
  );

  public function save(PropelPDO $con = null) {
	  if($this->isNew()) {
      $this->setRank(self::$slotToRankTranslationTable[$this->getSlot()]);
    }
    parent::save($con);
  }

} // WowCharacterItem
