<?php


/**
 * Skeleton subclass for representing a row from the 'wow_class_spec' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * pon, 8 mar 2010, 22:54:26
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowClassSpec extends BaseWowClassSpec {
  
} // WowClassSpec
