<?php


/**
 * Skeleton subclass for performing query and update operations on the 'wow_character' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * sob, 6 mar 2010, 20:39:10
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowCharacterQuery extends BaseWowCharacterQuery {

	/**
	 * Returns a new WowCharacterQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    WowCharacterQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof WowCharacterQuery) {
			return $criteria;
		}
		$query = new self();
		if (null !== $modelAlias) {
			$query->setModelalias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

  public function filterByArmory(cre8WowArmory $wowArmory, $name) {
    return $this->filterByName($name)
                    ->filterByWowZone(WowZoneQuery::create()->filterByName($wowArmory->getRegion())->findOne())
                    ->filterByWowRealm(WowRealmQuery::create()->filterByName($wowArmory->getServer())->findOne());
  }

  /**
	 * Returns a new WowCharacterQuery object joined with all possible relationes.
	 *
	 * @param     integer $wow_character_id WoWCharacter ID number
	 *
	 * @return    WowCharacterQuery Returns a new WowCharacterQuery object.
	 */
  public function filterByPrimaryKeyJoinWithAll($wow_character_id)
  {
    return $this->filterByPrimaryKey($wow_character_id)
            ->setFormatter(ModelCriteria::FORMAT_ON_DEMAND)
            ->joinWith('WowCharacter.WowZone')
            ->joinWith('WowCharacter.WowRealm')
            ->joinWith('WowCharacter.WowFaction')
            ->joinWith('WowCharacter.WowRace')
            ->joinWith('WowCharacter.WowClass')
            ->joinWith('WowCharacter.WowGender')
//            ->joinWith('WowCharacter.WowGuildMember')
//            ->joinWith('WowGuildMember.WowGuildMemberRole')
//            ->joinWith('WowGuildMember.WowGuild')
//            ->joinWith('WowGuild.WowGuildRank')
            ;
  }

} // WowCharacterQuery
