<?php


/**
 * Skeleton subclass for performing query and update operations on the 'wow_guild_member_role' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * nie, 14 mar 2010, 21:44:14
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowGuildMemberRolePeer extends BaseWowGuildMemberRolePeer {

} // WowGuildMemberRolePeer
