<?php


/**
 * Skeleton subclass for performing query and update operations on the 'wow_gender' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * sob, 6 mar 2010, 20:39:09
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowGenderPeer extends BaseWowGenderPeer {

} // WowGenderPeer
