<?php


/**
 * Skeleton subclass for performing query and update operations on the 'wow_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * nie, 7 mar 2010, 22:52:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowItemPeer extends BaseWowItemPeer {

} // WowItemPeer
