<?php


/**
 * Skeleton subclass for representing a row from the 'wow_item' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * nie, 7 mar 2010, 22:52:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowItem extends BaseWowItem {

  protected function doSave(PropelPDO $con) {
    if( ($this->isNew() || in_array(WowItemPeer::ICON, $this->getModifiedColumns())) && $this->getIcon()) {
      
      $this->setIcon($this->getIcon() . '.jpg');

      // Create a stream
      $opts = array(
              'http'=>array(
                      'method'=>"GET",
                      'header'=>"Accept-language: en\r\n" .
                              "User-Agent: Mozilla/5.0 (X11; U; Linux x86_64; pl-PL; rv:1.9.1.8) Gecko/20100214 Ubuntu/9.10 (karmic) Firefox/3.5.8\r\n"
              )
      );

      $context = stream_context_create($opts);
      
      // Open the file using the HTTP headers set above
      $icon = file_get_contents('http://eu.wowarmory.com/wow-icons/_images/64x64/' . $this->getIcon(), false, $context);
      if(file_put_contents(sfConfig::get('sf_web_dir').'/images/armory/64x64/' . $this->getIcon(), $icon)) {
        $thumbnail = new sfThumbnail(51, 51, true, false, 90);
        $thumbnail->loadFile(sfConfig::get('sf_web_dir').'/images/armory/64x64/'.$this->getIcon());
        $thumbnail->save(sfConfig::get('sf_web_dir').'/images/armory/51x51/'.$this->getIcon());

        $thumbnail = new sfThumbnail(21, 21, true, false, 90);
        $thumbnail->loadFile(sfConfig::get('sf_web_dir').'/images/armory/64x64/'.$this->getIcon());
        $thumbnail->save(sfConfig::get('sf_web_dir').'/images/armory/21x21/'.$this->getIcon());
        
        $thumbnail->freeAll();
        unset($thumbnail);
      }
      unset($icon);

    }
    return parent::doSave($con);
  }


} // WowItem
