<?php


/**
 * Skeleton subclass for representing a row from the 'wow_realm' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * sob, 6 mar 2010, 20:39:09
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WowRealm extends BaseWowRealm {

} // WowRealm
